### ISSUE TITLE
Pay transaction fees by non-native token

### ISSUE THREAD

**Issue by Dengjianping** [Manta-Network/Manta#776] opened 2022-08-29 01:36 UTC
We have integrated pallet-assets and xcm enabled.
Maybe it's time to discuss integrate this pallet: [asset-tx-payment](https://github.com/paritytech/substrate/tree/master/frame/transaction-payment/asset-tx-payment)

**Comment by ghzlatarev** [comment] 2022-08-29 06:40
Duplicate of https://github.com/Manta-Network/Manta/issues/595

**Closed as completed by ghzlatarev** 2022-08-29 06:40 UTC
Labels: A-calamari, A-runtime
