### ISSUE TITLE
Better Integration Test

### ISSUE THREAD

**Issue by stechu** [Manta-Network/Manta#370] opened 2022-01-28 02:36 UTC
Many things currently we do in QA test can be performed in an automated fashion, for example:

https://github.com/PureStake/moonbeam/blob/master/runtime/moonbeam/tests/integration_test.rs

Related to #347

**Comment by ghzlatarev** [comment] 2022-01-28 07:42
Duplicate of https://github.com/Manta-Network/Manta/issues/347

**Comment by ghzlatarev** [comment] 2022-01-28 17:32
Not a duplicate. my bad.

**Closed as completed** 2022-03-02 23:20 UTC
Labels: A-automation, A-ci, P-medium
