### ISSUE TITLE
Benchmark `cumulus_pallet_xcmp_queue`

### ISSUE THREAD

**Issue by Dengjianping** [Manta-Network/Manta#537] opened 2022-05-09 13:27 UTC
After v0.9.18, this pallet introduced a new associated type `WeightInfo`, so we need to benchmark it.
Our CI need to support it.

**Comment by ghzlatarev** [comment] 2022-06-06 06:46
This is a dupe of https://github.com/Manta-Network/Manta/pull/554

**Closed as completed** 2022-06-07 08:10 UTC
Labels: A-calamari, A-ci
